# upstream api_backend {
#     server taskapi-svc:8080;
# }

server {
    listen 80;
    server_name localhost;
    resolver kube-dns.kube-system.svc.cluster.local valid=10s;


    # 前端静态文件
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 代理 API 请求到后端容器（关键！）
    location /api/ {
        # proxy_pass http://api_backend/api/;
        # proxy_set_header Host $host;
        # proxy_set_header X-Real-IP $remote_addr;
        # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://api_backend/api/;
        proxy_http_version 1.1;                      # 必须使用 HTTP 1.1
        proxy_set_header Upgrade $http_upgrade;      # 传递 Upgrade 头
        proxy_set_header Connection "Upgrade";       # 传递 Connection: Upgrade
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}