services:
  postgres_db:
    image: postgres:16-alpine
    container_name: my-postgres-compose
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-dev-network

  taskmanagementapi_1:
    image: ${DOCKER_USERNAME}/taskapi:${TAG:-latest}
    # build:
    #   context: ./TaskManagementAPI
    #   dockerfile: Dockerfile
    container_name: my-taskapi-compose-1
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Redis__ConnectionString=redis-sentinel-1:26379,redis-sentinel-2:26379,redis-sentinel-3:26379,serviceName=mymaster,password=${REDIS_PASSWORD}
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=${RABBITMQ_USER}
      - RabbitMQ__Password=${RABBITMQ_PASSWORD}
      - ASPNETCORE_URLS=http://+:8080
    healthcheck:
     test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/8080' || exit 1"]
     interval: 10s
     timeout: 5s
     retries: 3
     start_period: 30s
    depends_on:
      - postgres_db
      - redis_master
      - redis_slave_1
      - redis_slave_2
      - redis_sentinel_1
      - redis_sentinel_2
      - redis_sentinel_3
      - rabbitmq 
    networks:
      - my-dev-network

  taskmanagementapi_2:
    image: ${DOCKER_USERNAME}/taskapi:${TAG:-latest}
    # build:
    #   context: ./TaskManagementAPI
    #   dockerfile: Dockerfile
    container_name: my-taskapi-compose-2
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Redis__ConnectionString=redis-sentinel-1:26379,redis-sentinel-2:26379,redis-sentinel-3:26379,serviceName=mymaster,password=${REDIS_PASSWORD}
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=${RABBITMQ_USER}
      - RabbitMQ__Password=${RABBITMQ_PASSWORD}
      - ASPNETCORE_URLS=http://+:8080
    healthcheck:
     test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/8080' || exit 1"]
     interval: 10s
     timeout: 5s
     retries: 3
     start_period: 30s
    depends_on:
      - postgres_db
      - redis_master
      - redis_slave_1
      - redis_slave_2
      - redis_sentinel_1
      - redis_sentinel_2
      - redis_sentinel_3
      - rabbitmq 
    networks:
      - my-dev-network

  frontend:
    build:
      context: ../../React/task-management-frontend-redux-ts 
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: my-frontend
    ports:
      - "5173:80"
    depends_on:
      - taskmanagementapi_1
      - taskmanagementapi_2
    networks:
      - my-dev-network

  redis_master:
    image: redis:7-alpine
    container_name: redis-master
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --masterauth ${REDIS_PASSWORD}
      --appendonly yes
      --appendfsync everysec
      --save 900 1
      --save 300 10
      --save 60 10000
      --min-replicas-to-write 1
      --min-replicas-max-lag 10
    volumes:
      - redis-master-data:/data
    networks: 
      - my-dev-network
  
  redis_slave_1:
    image: redis:7-alpine
    container_name: redis-slave-1
    ports:
      - "6380:6379"
    command: >
      redis-server
      --slaveof redis_master 6379
      --requirepass ${REDIS_PASSWORD}
      --masterauth ${REDIS_PASSWORD}
    depends_on: 
      redis_master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks: 
      - my-dev-network

  redis_slave_2:
    image: redis:7-alpine
    container_name: redis-slave-2
    ports:
      - "6381:6379"
    command: redis-server --slaveof redis_master 6379 --requirepass ${REDIS_PASSWORD} --masterauth ${REDIS_PASSWORD}
    depends_on: 
      redis_master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks: 
      - my-dev-network

  redis_sentinel_1:
    build:
      context: ./redis
      dockerfile: Dockerfile-sentinel
    # image: redis:7-alpine
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    command: []
    # volumes:
    #   - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      redis_master:
        condition: service_healthy
      redis_slave_1:
        condition: service_healthy
      redis_slave_2:
        condition: service_healthy
    restart: always
    networks:
      - my-dev-network 

  redis_sentinel_2:
    build:
      context: ./redis
      dockerfile: Dockerfile-sentinel
    # image: redis:7-alpine
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    command: []
    # volumes:
    #   - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      redis_master:
        condition: service_healthy
      redis_slave_1:
        condition: service_healthy
      redis_slave_2:
        condition: service_healthy
    restart: always
    networks:
      - my-dev-network 

  redis_sentinel_3:
    build:
      context: ./redis
      dockerfile: Dockerfile-sentinel
    # image: redis:7-alpine
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"
    command: []
    # volumes:
    #   - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      redis_master:
        condition: service_healthy
      redis_slave_1:
        condition: service_healthy
      redis_slave_2:
        condition: service_healthy
    restart: always
    networks:
      - my-dev-network 

  # redis_cache:
  #   image: redis:7-alpine
  #   container_name: my-redis-compose
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - my-dev-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: my-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    networks:
      - my-dev-network

  # rabbitmq1:
  #   image: rabbitmq:3-management-alpine
  #   hostname: rabbitemq1
  #   environment:
  #     RABBITMQ_ERLANG_COOKIE: "secret-cookie-here"
  #     RABBITMQ_DEFAULT_USER: admin
  #     RABBITMQ_DEFAULT_PASS: 123456
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   volumes:
  #     - ./data/rabbitmq1:/var/lib/rabbitmq

  # rabbitmq2:
  #   image: rabbitmq:3-management-alpine
  #   hostname: rabbitemq2
  #   environment:
  #     RABBITMQ_ERLANG_COOKIE: "secret-cookie-here"
  #     RABBITMQ_DEFAULT_USER: admin
  #     RABBITMQ_DEFAULT_PASS: 123456
  #   volumes:
  #     - ./data/rabbitmq1:/var/lib/rabbitmq

  # rabbitmq3:
  #   image: rabbitmq:3-management-alpine
  #   hostname: rabbitemq3
  #   environment:
  #     RABBITMQ_ERLANG_COOKIE: "secret-cookie-here"
  #     RABBITMQ_DEFAULT_USER: admin
  #     RABBITMQ_DEFAULT_PASS: 123456
  #   volumes:
  #     - ./data/rabbitmq1:/var/lib/rabbitmq

  # haproxy:
  #   image: haproxy:latest
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   volumes:
  #     - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  #   depends_on:
  #     - rabbitmq1
  #     - rabbitmq2
  #     - rabbitmq3

  rabbitmqconsumer:
    image: ${DOCKER_USERNAME}/rabbitmqconsumer:${TAG:-latest}
    # build:
    #   context: ./RabbitMQConsumer
    #   dockerfile: Dockerfile
    container_name: my-consumer
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=admin
      - RabbitMQ__Password=123456
    depends_on:
      - rabbitmq
    networks:
      - my-dev-network

networks:
  my-dev-network:
    driver: bridge

volumes:
  postgres-data:
  redis-master-data:
  redis-slave-1-data:
  redis-slave-2-data: