name: CI - Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore TaskManagementAPI/TaskManagementAPI.csproj

      - name: Build
        run: dotnet build TaskManagementAPI/TaskManagementAPI.csproj --no-restore -c Release

  build-consumer:
    name: Build Consumer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore RabbitMQConsumer/RabbitMQConsumer.csproj

      - name: Build
        run: dotnet build RabbitMQConsumer/RabbitMQConsumer.csproj --no-restore -c Release